# Generated by Django 6.1 on 2026-08-25 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_employee_assetassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('returned', 'Returned'), ('maintenance', 'Maintenance'), ('status_change', 'Status Change'), ('location_change', 'Location Change'), ('retired', 'Retired')], max_length=30)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.asset')),
            ],
            options={
                'verbose_name_plural': 'Asset History',
                'ordering': ['-created_at'],
            },
        ),
    ]
