# Generated by Django 6.1 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


def convert_old_values(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    Employee = apps.get_model("assets", "Employee")
    Department = apps.get_model("assets", "Department")
    Location = apps.get_model("assets", "Location")

    # Convert existing Employee.department text values
    for employee in Employee.objects.all():
        old_department = employee.department

        if not old_department:
            continue

        # If the department already exists by name, use it.
        department = Department.objects.filter(
            name=old_department
        ).first()

        # Otherwise create a Department from the old text.
        if department is None:
            code = old_department[:20].upper().replace(" ", "_")

            # Make sure the generated code is unique.
            original_code = code
            counter = 1

            while Department.objects.filter(code=code).exists():
                code = f"{original_code[:17]}_{counter}"
                counter += 1

            department = Department.objects.create(
                name=old_department,
                code=code,
            )

        # At this stage department is still a CharField.
        employee.department = department.pk
        employee.save(update_fields=["department"])

    # Convert existing Asset.location text values
    for asset in Asset.objects.all():
        old_location = asset.location

        if not old_location:
            continue

        # If the location already exists by name, use it.
        location = Location.objects.filter(
            name=old_location
        ).first()

        # Otherwise create a Location from the old text.
        if location is None:
            location = Location.objects.create(
                name=old_location,
            )

        # At this stage location is still a CharField.
        asset.location = location.pk
        asset.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_department_location"),
    ]

    operations = [
        migrations.RunPython(
            convert_old_values,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="assets.location",
            ),
        ),

        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="assets.department",
            ),
        ),
    ]