# Generated by Django 6.1 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


def convert_old_categories(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    Category = apps.get_model("assets", "Category")

    for asset in Asset.objects.all():
        old_category = asset.category

        if not old_category:
            continue

        # Find an existing category with the same name.
        category = Category.objects.filter(
            name=old_category
        ).first()

        # If it doesn't exist, create it.
        if category is None:
            code = old_category[:20].upper().replace(" ", "_")

            original_code = code
            counter = 1

            while Category.objects.filter(code=code).exists():
                code = f"{original_code[:17]}_{counter}"
                counter += 1

            category = Category.objects.create(
                name=old_category,
                code=code,
            )

        # The database column is still text at this point.
        # Store the Category primary key temporarily.
        asset.category = category.pk
        asset.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_category"),
    ]

    operations = [
        migrations.RunPython(
            convert_old_categories,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="assets.category",
            ),
        ),
    ]


    